<a href="https://colab.research.google.com/github/imshiv-10/Data-Analysis/blob/main/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [ ]:
!pip install jovian --upgrade -q

     |████████████████████████████████| 68 kB 3.2 MB/s 


In [ ]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [ ]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.concatenate  # (change this)
function2 = np.tile
function3 = np.dtype
function4 = np.shape
function5 = np.matmul

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [ ]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

1. In above snippet arr1 is appending with arr2, while it's shapes are matches according to axis it will works without any issues

In [ ]:
# Example 2 - working

arr1 = [[1, 2, 3], 
        [3, 4. , 4]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

array([[ 1.,  2.,  3.],
       [ 3.,  4.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

Explanation about example



In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example (why it breaks and how to fix it)

1. In arr1 matrix shape is (2,2) but arr2 matrix it's having the (2,3) here axis as 0 so, we are appending arr2 rows into arr1 the shapes are missmatching it will not do this above operation
2. we fix above snippet by axis =1 its means appending to the column level

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 2 - ???

Add some explanations

In [ ]:
# Example 1 - working

arr1 = np.zeros((4,4))
arr2 = np.tile(arr1, (2,2))
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

Explanation about example
In above function we have used tile function it will extend the given matrix

In [ ]:
# Example 2 - working
arr1 = np.array([[2, 0], [0,2]])
z = np.tile(arr1, (4,4))
z

array([[2, 0, 2, 0, 2, 0, 2, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [2, 0, 2, 0, 2, 0, 2, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [2, 0, 2, 0, 2, 0, 2, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [2, 0, 2, 0, 2, 0, 2, 0],
       [0, 2, 0, 2, 0, 2, 0, 2]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.ones((1,1))
z = np.tile(arr1, (4,4))
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [ ]:
# Example 1 - working
x = np.array([[1,2,3,4.],[1,2,3,4]])
x

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>